name: build
on:
  push:
    branches:
      - master
  pull_request:
env:
  NODE_VERSION: "18.20.4"

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        runner: [bronley-a1, bronley-a2, bronley-a3, bronley-a4, bronley-a5, bronley-a6, bronley-a7, bronley-b1]
    name: ci (${{ matrix.runner }})
    runs-on: [self-hosted, "${{ matrix.runner }}"]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Load local npm cache for node ${{ env.NODE_VERSION }}
        uses: MasterworksIO/action-local-cache@2
        with:
          path: .npm
          key: ${{ env.NODE_VERSION }}
          strategy: move
      - run: npm ci --cache .npm
      - run: npm run build
      - run: npm run test
      - run: npm run test-package
