name: build
on:
  push:
    branches:
      - master
  pull_request:
env:
  NODE_VERSION: "18.20.4"

jobs:
  ci:
    runs-on: [self-hosted, roku-latest, enabled]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Load local npm cache for node ${{ env.NODE_VERSION }}
        uses: MasterworksIO/action-local-cache@2
        with:
          path: .npm
          key: ${{ env.NODE_VERSION }}
          strategy: move
      - run: npm ci --cache .npm
      - run: npm run build
      - run: npm run test
      - name: Upload coverage to Coveralls
        #upload coverage even when tests fail, so a red run still reports its numbers
        if: always()
        uses: coverallsapp/github-action@v2
        env:
          #hardcode the coveralls token...it's not overly important to protect, and github actions won't allow forks to work with coveralls otherwise
          COVERALLS_REPO_TOKEN: "NXvWn0KVUALZKtbSHGiK3vLDYvd6qqMCg"
        with:
          path-to-lcov: ./coverage/lcov.info
      - run: npm run test-package
